# Describes the format for available ostrom services

ostrom_apitest_error:
  name: API Test Error
  description: Simuliere einen API-Fehler für Testzwecke
  fields:
    simulate_error:
      required: true
      selector:
        boolean:
    clear_last_data:
      required: false
      default: false
      selector:
        boolean:
